services:
  rabbitmq-1: &rabbitmq-common
    image: "rabbitmq:4-management-alpine"
    restart: always
    hostname: rabbitmq-1
    container_name: rabbitmq-1
    environment: &rabbitmq-env
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 74faa001f5ba434d
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_ERLANG_COOKIE: 40556c104edf7359de6a595c
    volumes:
      - rabbitmq-1_data:/var/lib/rabbitmq/mnesia
    command: >
      sh -c "
      apk add --no-cache curl &&
      curl -Lo plugins/rabbitmq_delayed_message_exchange.ez
      https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v4.0.2/rabbitmq_delayed_message_exchange-4.0.2.ez &&
      rabbitmq-plugins enable rabbitmq_delayed_message_exchange &&
      rabbitmq-server"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - production

  rabbitmq-2: &rabbitmq-slave
    <<: *rabbitmq-common
    hostname: rabbitmq-2
    container_name: rabbitmq-2
    environment:
      <<: *rabbitmq-env
    volumes:
      - rabbitmq-2_data:/var/lib/rabbitmq/mnesia
    command: >
      sh -c "
      apk add --no-cache curl &&
      curl -Lo plugins/rabbitmq_delayed_message_exchange.ez
      https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v4.0.2/rabbitmq_delayed_message_exchange-4.0.2.ez &&
      rabbitmq-plugins enable rabbitmq_delayed_message_exchange &&
      rabbitmq-server -detached &&
      sleep 10 &&
      rabbitmqctl stop_app &&
      rabbitmqctl join_cluster rabbit@rabbitmq-1 &&
      rabbitmqctl start_app &&
      rabbitmqctl stop &&
      exec rabbitmq-server"
    depends_on:
      rabbitmq-1:
        condition: service_healthy

  rabbitmq-3:
    <<: *rabbitmq-slave
    hostname: rabbitmq-3
    container_name: rabbitmq-3
    volumes:
      - rabbitmq-3_data:/var/lib/rabbitmq/mnesia

  haproxy-rabbitmq:
    image: "haproxy:latest"
    container_name: haproxy-rabbitmq
    ports:
      - "1936:1936"
      - "15872:15672"
    volumes:
      - ./../infra/rabbitmq-ha/haproxy-rabbitmq.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      rabbitmq-1:
        condition: service_healthy
      rabbitmq-2:
        condition: service_healthy
      rabbitmq-3:
        condition: service_healthy
    networks:
      - production

volumes:
  rabbitmq-1_data:
  rabbitmq-2_data:
  rabbitmq-3_data:

networks:
  production:
    name: production
    external: true
